### ISSUE TITLE
Fallback to default component if module does not exists.

### ISSUE THREAD

**Issue by tayfunyasar** [ganapativs/react-dynamic-import#49]
How can i do it?

**Comment by ganapativs** [comment]
Yes. Pass the `errorHandler` option. Check out the [API](https://github.com/ganapativs/react-dynamic-import/blob/master/docs/react-dynamic-import.md) docs.

**Comment by ganapativs** [comment]
I hope this solved the issue. closing for now. re-open if something doesn't work as expected.
